branch-defaults:
  master:
    environment: Cyberarc-env-2
environment-defaults:
  Cyberarc-env-2:
    branch: master
    repository: awsebs
global:
  application_name: CyberArc
  default_ec2_keyname: null
  default_platform: PHP 7.4 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
